// <auto-generated />
namespace MyPortfolioWebForm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class nbm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nbm));
        
        string IMigrationMetadata.Id
        {
            get { return "201912240902492_nbm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
